# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Go environment
      run: |
        cd /
        sudo mkdir -p /goroot
        curl https://storage.googleapis.com/golang/go1.14.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
        export GOROOT=/goroot
        export GOPATH=/gopath
        export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
        echo 'done'
        
        
        

#     - name: Test with pytest
#       run: |
#         python test.py
